[package]
name = "DRIP"
description = "DRIP - Dynamic Randomised Item Properties, adds random Diablo 2 style enchantments to spawned items."
homepage = "https://www.nexusmods.com/morrowind/mods/51242"
repository = "https://github.com/jhaakma/drip"
authors = [ "Merlord",]
version = "1.3.1"

[dependencies]
assets = [ "Icons/drip", "Meshes/drip", "MWSE/mods/mer/drip", "Textures/drip",]

[dependencies.mwse]
buildnumber = 3519

[dependencies.mge-xe]
version = ">=0.15.0"

[tools.mwse]
lua-mod = "mer.drip"
